### ISSUE TITLE
Missing troubleshoot_summary file

### ISSUE THREAD

**Issue by checheanya** [kelwyres/Bactabolize#28]
Hello! 
I have been running Bactabolize using the custom media with the following command:

```
bactabolize draft_model \
    --assembly_fp $assmebly \
    --ref_genbank_fp ref_seqs/saureus.gb \
    --ref_model_fp ref_models/iYS854_saureus.json \
    --media_type enterococc \
    --atmosphere_type aerobic \
    --output_fp wgs659 \
    --min_coverage 25 \
    --min_ppos 80
```

The run failed with the output and error as follows. It was stated in the error message that the model could be patched via patch_model using the file wgs659_model.json.troubleshoot_summary.txt, however, this file was never created and as the output I have only files wgs659_gene_dictionary.csv , wgs659_model.xml, wgs659_model.json, and wgs659_unannotated_sequences.fasta created. 

How would you recommend to resolve this issue?

Thanks!

Error:

```
warning: could not find model 5 entries in reference genes: USA300HOU_RS14510, USA300HOU_2188, USA300HOU_RS14515, s0001, USA300HOU_2187
warning: could not find model 5 entries in reference proteins: USA300HOU_RS14510, USA300HOU_2188, USA300HOU_RS14515, s0001, USA300HOU_2187
warning: draft model does not contain reaction EX_cysi__L_e
warning: draft model does not contain reaction EX_13BDglcn_e
warning: draft model does not contain reaction EX_amp_e
warning: draft model does not contain reaction EX_cbl1_e
warning: draft model does not contain reaction EX_cmp_e
warning: draft model does not contain reaction EX_glycogen_e
warning: draft model does not contain reaction EX_gmp_e
warning: draft model does not contain reaction EX_h2s_e
warning: draft model does not contain reaction EX_mannan_e
warning: draft model does not contain reaction EX_pail160_e
warning: draft model does not contain reaction EX_pchol_cho_e
warning: draft model does not contain reaction EX_pe_cho_e
warning: draft model does not contain reaction EX_pydxn_e
warning: draft model does not contain reaction EX_sel_e
warning: draft model does not contain reaction EX_slnt_e
warning: draft model does not contain reaction EX_ump_e
warning: draft model does not contain reaction EX_chsterol_e
warning: draft model does not contain reaction EX_tchola_e
warning: draft model does not contain reaction EX_gchola_e
warning: draft model does not contain reaction EX_cit_e
warning: draft model does not contain reaction EX_escul_e
error: wgs659 model failed to produce biomass on minimal media, construct patch.json manually using wgs659_model.json.troubleshoot_summary.txt and fix draft wgs659 model via patch_model command
Traceback (most recent call last):
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/bin/bactabolize", line 10, in <module>
    sys.exit(entry())
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/__main__.py", line 23, in entry
    run_draft_model(config)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/__main__.py", line 73, in run_draft_model
    draft_model.run(config)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 73, in run
    assess_model(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 132, in assess_model
    create_troubleshooter(model, model_draft, blast_results, biomass_reaction_id, f'{output_fp}.troubleshoot')
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 150, in create_troubleshooter
    reactions_missing, gapfilled, nonzero_threshold = gapfill_model(model, model_draft)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 219, in gapfill_model
    gapfilled = gapfiller.fill(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/flux_analysis/gapfilling.py", line 252, in fill
    self.model.slim_optimize(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/core/model.py", line 1082, in slim_optimize
    assert_optimal(self, message)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/util/solver.py", line 544, in assert_optimal
    raise exception_cls(f"{message} ({status}).")
cobra.exceptions.Infeasible: gapfilling optimization failed (infeasible).
```

**Comment by bananabenana** [comment]
Hi @checheanya,

There appear to be a few different error messages here.

# Note 1

With your command, can you confirm that this is not a typo:
`--assembly_fp $assmebly` and not `--assembly_fp $assembly`?

# Error 1
```bash
warning: could not find model 5 entries in reference genes: USA300HOU_RS14510, USA300HOU_2188, USA300HOU_RS14515, s0001, USA300HOU_2187
```
Can you confirm that your `--ref_genbank_fp saureus.gb` matches your `--ref_model_fp iYS854_saureus.json`? If there are genes in your model that are missing from your genbank file, then this warning will pop up. Is your current genbank file is https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000017085.1/ and do all your protein gene names match the model gene names in the .json?

## Proposed solution
- It may be easier to resolve this by using the  `--ref_genes_fp` AND `--ref_proteins_fp`. instead of the `--ref_genbank_fp` option. These will just be multifasta files containing the DNA and protein sequences for the model genes found in `iYS854_saureus.json` and doing it this way allows you to ensure that you get all the relevant model genes.
- You have not specified a biomass objective function. Looking at [iYS854](http://bigg.ucsd.edu/models/iYS854) it appears to have 13 different biomass objective functions. The `BIOMASS_WT_lumped` function appears to be a combined version of all 13 other ones, so I would try the following:
```bash
# Create draft model
bactabolize draft_model \
    --assembly_fp $assembly \ # Changed $assmebly to $assembly
    --ref_genes_fp iYS854_saureus_prots.ffn \ # added this line and replaced ref_genbank_fp 
    --ref_proteins_fp iYS854_saureus_genes.faa \ # added this line
    --ref_model_fp iYS854_saureus.json \
    --biomass_reaction_id BIOMASS_WT_lumped \ # added this line
    --media_type enterococc \
    --atmosphere_type aerobic \
    --min_coverage 25 \
    --min_ppos 80 \
    --output_fp wgs659
```

# Error 2
```bash
warning: draft model does not contain reaction EX_cysi__L_e
```
This occurs when your growth media contains components that your model can't use, as it doesn't have those exchange reactions encoded. 

## Proposed solution
This is not a bad thing, but if you think your model should contain them, consider adding them in. Especially if there are reactions which use for example, `cysi__L_c` or `cysi__L_p`

# Error 3
```bash
error: wgs659 model failed to produce biomass on minimal media, construct patch.json manually using wgs659_model.json.troubleshoot_summary.txt and fix draft wgs659 model via patch_model command
Traceback (most recent call last):
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/bin/bactabolize", line 10, in <module>
    sys.exit(entry())
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/__main__.py", line 23, in entry
    run_draft_model(config)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/__main__.py", line 73, in run_draft_model
    draft_model.run(config)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 73, in run
    assess_model(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 132, in assess_model
    create_troubleshooter(model, model_draft, blast_results, biomass_reaction_id, f'{output_fp}.troubleshoot')
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 150, in create_troubleshooter
    reactions_missing, gapfilled, nonzero_threshold = gapfill_model(model, model_draft)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/bactabolize/draft_model.py", line 219, in gapfill_model
    gapfilled = gapfiller.fill(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/flux_analysis/gapfilling.py", line 252, in fill
    self.model.slim_optimize(
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/core/model.py", line 1082, in slim_optimize
    assert_optimal(self, message)
  File "/mnt/lustre/home/steinthoeringer/stech216/mambaforge/envs/bactabolize_env/lib/python3.9/site-packages/cobra/util/solver.py", line 544, in assert_optimal
    raise exception_cls(f"{message} ({status}).")
cobra.exceptions.Infeasible: gapfilling optimization failed (infeasible).
```

Without seeing your files, I can't say right now. My guess is that your draft model is unable to grow even after minimal gap filling simulations, because too many key reactions are missing or because the appropriate biomass objective value hasn't been selected. This may be linked to those 5 missing genes in your reference protein/CDS files.

If the previous solutions don't help you, you can send me your custom media, reference genbank file, reference model and input assembly and I can have a tinker.


Thanks

**Comment by bananabenana** [comment]
Closing due to inactivity. Please re-open if issue unresolved.
